FROM node:20-slim

RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY stream-proxy.js ./

EXPOSE 10000

CMD ["node", "stream-proxy.js"]